# Generated by Django 4.1.3 on 2023-07-20 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_objectifhebdo_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatligne',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ligneprod',
            name='commentaire',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
