# Generated by Django 4.1.3 on 2023-07-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_objectifhebdo_numero_semaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectifhebdo',
            name='numero_semaine',
            field=models.IntegerField(default=1),
        ),
    ]
