# Generated by Django 4.1.3 on 2023-07-20 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('OK', 'OK'), ('KO', 'KO')], max_length=2)),
                ('commentaire', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectifHebdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(choices=[('Airbus', 'Airbus'), ('Boeing', 'Boeing'), ('Comac', 'Comac')], max_length=30)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('objectif_hebdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.objectifhebdo')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('ligne_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='product.ligneprod')),
            ],
        ),
        migrations.AddField(
            model_name='objectifhebdo',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produit'),
        ),
        migrations.AddField(
            model_name='objectifhebdo',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MouvementTempsReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.IntegerField()),
                ('soustraction', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EtatLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=300)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('OK', 'OK'), ('KO', 'KO')], default='OK', max_length=2)),
                ('ligne_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ligneprod')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
