# Generated by Django 4.1.3 on 2023-07-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_etatligne_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectifhebdo',
            name='numero_semaine',
            field=models.IntegerField(default=29),
        ),
    ]
