# Generated by Django 4.1.3 on 2023-07-24 11:18

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_objectifhebdo_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_to),
        ),
    ]
